import type {Lang} from './content';
export const experience = {
 en: {headline:'Plumbing help.\nA clear next step.',intro:'Leaks, upgrades, or something not quite right? Find the service your home or business needs.',start:'What needs attention?',startHint:'Choose what you’re noticing. You can change it later.',recommend:'A place to start',chooseProperty:'Where do you need help?',continue:'Continue with this service',change:'Explore the service first',notDiagnosis:'Your selection helps explain the request. The cause and work needed require an evaluation.',intent:'What would you like to do?',serviceIntent:'Request service',quoteIntent:'Request a quote',optional:'(optional)',contactHint:'Only your preferred contact method is required.',all:'All services',repair:'Leaks & drainage',install:'Installations & fixtures',comfort:'Hot water & water control',prepare:'What to have ready',scope:'Plan the next step with clarity.',scopeText:'Share the symptoms, your location, and any access considerations. The work and availability are reviewed before an appointment is confirmed.',learn:'Understand this service',count:'services',related:'You may also need',proof:'Get to know Aqua Pro',pricing:'Pricing guidance',conditions:'Service conditions',team:'Our team',reviews:'Customer experiences',coverage:'Confirm your service area',coverageText:'Tell us your city or ZIP code. We’ll use it to review coverage, without assuming your location is already served.',photo:'Illustrative image',contactTitle:'Let’s understand\nwhat you need.',summary:'Your request',draft:'Your details stay here while you switch languages. Reloading or closing the page clears this demo form.'},
 es: {headline:'Tu plomería.\nEl siguiente paso, claro.',intro:'¿Una fuga, una renovación o algo que no funciona? Encuentra el servicio que necesita tu hogar o negocio.',start:'¿Qué necesita atención?',startHint:'Elige lo que ocurre. Puedes cambiarlo después.',recommend:'Un punto de partida',chooseProperty:'¿Dónde necesitas ayuda?',continue:'Continuar con este servicio',change:'Conocer primero el servicio',notDiagnosis:'Tu selección ayuda a explicar la solicitud. La causa y el trabajo necesario requieren una evaluación.',intent:'¿Qué te gustaría hacer?',serviceIntent:'Solicitar servicio',quoteIntent:'Solicitar cotización',optional:'(opcional)',contactHint:'Solo es obligatorio el medio de contacto que prefieras.',all:'Todos los servicios',repair:'Fugas y drenaje',install:'Instalaciones y accesorios',comfort:'Agua caliente y bombeo',prepare:'Qué información preparar',scope:'Planifica el siguiente paso con claridad.',scopeText:'Comparte los síntomas, tu ubicación y las condiciones de acceso. El trabajo y la disponibilidad se revisan antes de confirmar una cita.',learn:'Conocer este servicio',count:'servicios',related:'También podrías necesitar',proof:'Conoce Aqua Pro',pricing:'Información de precios',conditions:'Condiciones del servicio',team:'Nuestro equipo',reviews:'Experiencias de clientes',coverage:'Consulta la cobertura',coverageText:'Indica tu ciudad o código postal para revisar la cobertura, sin asumir que tu ubicación ya está incluida.',photo:'Imagen ilustrativa',contactTitle:'Comprendamos\nqué necesitas.',summary:'Tu solicitud',draft:'Tus datos se conservan al cambiar de idioma. Al recargar o cerrar la página se borra este formulario de demostración.'}
};
export const serviceGroups:Record<string,'repair'|'install'|'comfort'>={'new-plumbing':'install','leak-detection':'repair','drain-cleaning':'repair','fixture-installation':'install','water-heaters':'comfort','camera-inspection':'repair','sump-pumps':'comfort'};
export const relatedServices:Record<string,string[]>={
 'new-plumbing':['fixture-installation','water-heaters','drain-cleaning'],
 'leak-detection':['camera-inspection','fixture-installation','new-plumbing'],
 'drain-cleaning':['camera-inspection','leak-detection','sump-pumps'],
 'fixture-installation':['new-plumbing','leak-detection','water-heaters'],
 'water-heaters':['leak-detection','new-plumbing','fixture-installation'],
 'camera-inspection':['drain-cleaning','leak-detection','new-plumbing'],
 'sump-pumps':['drain-cleaning','leak-detection','camera-inspection']
};
export const prepare:Record<string,Record<Lang,string[]>>={
 'new-plumbing':{en:['The rooms and fixtures in your plans','The stage of construction or renovation','Any layout plans available to discuss'],es:['Los espacios y accesorios del proyecto','La etapa de construcción o remodelación','Los planos disponibles para conversar']},
 'leak-detection':{en:['Where you noticed moisture or dripping','When it started and whether it is recurring','Any recent work near the affected area'],es:['Dónde notaste humedad o goteo','Cuándo comenzó y si es recurrente','Trabajos recientes cerca de la zona afectada']},
 'drain-cleaning':{en:['Which sinks, showers or drains are affected','Whether one or several drains are slow','What has already been tried'],es:['Qué fregaderos, duchas o desagües están afectados','Si el problema afecta uno o varios desagües','Qué se ha intentado hasta ahora']},
 'fixture-installation':{en:['The fixture type and model, if selected','Whether this is a replacement or new location','Details of the existing connections'],es:['Tipo y modelo del accesorio, si lo elegiste','Si es un reemplazo o una ubicación nueva','Detalles de las conexiones existentes']},
 'water-heaters':{en:['The equipment type and model, if known','Changes in temperature or hot-water supply','Any visible moisture around the unit'],es:['Tipo y modelo del equipo, si los conoces','Cambios de temperatura o suministro','Humedad visible alrededor del equipo']},
 'camera-inspection':{en:['The history of drainage problems','Known access points for the line','Any previous inspection findings'],es:['El historial de problemas de drenaje','Los puntos de acceso conocidos','Hallazgos de inspecciones anteriores']},
 'sump-pumps':{en:['The pump type, if known','What happens when water collects','Any unusual noise or cycling'],es:['El tipo de bomba, si lo conoces','Qué ocurre cuando se acumula agua','Ruidos o ciclos inusuales']}
};
export const media = {
 camera:{src:'camera.webp',en:'Illustrative drain inspection camera, monitor and cable reel',es:'Imagen ilustrativa de cámara de inspección, monitor y cable'},
 sump:{src:'sump.webp',en:'Illustrative sump basin, pump and discharge pipe',es:'Imagen ilustrativa de sumidero, bomba y tubería de descarga'},
 technician:{src:'plumber.webp',en:'Illustrative plumber inspecting connections under a kitchen sink',es:'Imagen ilustrativa de un técnico revisando conexiones bajo un fregadero'},
 kitchen:{src:'kitchen.webp',en:'Kitchen faucet and stainless steel sink',es:'Grifo de cocina y fregadero de acero'},
 bathroom:{src:'bathroom.webp',en:'Bathroom with bathtub and fixtures',es:'Baño con bañera y accesorios'},
 heater:{src:'heater.webp',en:'Illustrative residential electric water heater and pipe connections',es:'Imagen ilustrativa de un calentador eléctrico y sus conexiones'}
};
export type MediaKey=keyof typeof media;
export const serviceMedia:Record<string,MediaKey>={'new-plumbing':'bathroom','leak-detection':'technician','drain-cleaning':'kitchen','fixture-installation':'bathroom','water-heaters':'heater','camera-inspection':'camera','sump-pumps':'sump'};
