import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Site from '../../../components/Site';
import {Lang,Page,routes,services,serviceSlug,route,copy} from '../../../lib/content';
import {siteUrl} from '../../../lib/config';
import {businessStructuredData} from '../../../lib/structured-data';
export const dynamicParams=false;
export function generateStaticParams(){return (['en','es'] as Lang[]).flatMap(lang=>[...Object.keys(routes).map(p=>({lang,slug:route(lang,p).split('/').filter(Boolean).slice(1)})),...services.map(s=>({lang,slug:[lang==='en'?'services':'servicios',serviceSlug(s,lang)]}))]);}
function resolve(lang:Lang,slug:string[]=[]){const path=slug.join('/');const page=(Object.keys(routes) as Page[]).find(p=>routes[p][lang==='en'?0:1]===path);const service=services.find(s=>path===`${lang==='en'?'services':'servicios'}/${serviceSlug(s,lang)}`);return {page,service};}
type Props={params:Promise<{lang:string;slug?:string[]}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {lang:raw,slug}=await params;const lang=raw as Lang; if(!['en','es'].includes(lang))return {};const {page,service}=resolve(lang,slug);const t=copy[lang];const title=service?.[lang].name||({home:t.hero.replace('\n',' '),services:t.nav[1],residential:t.residential,commercial:t.commercial,about:t.nav[4],areas:t.areas,contact:t.request,privacy:t.privacy}[page||'home']);const description=service?.[lang].description||({home:t.intro,services:t.serviceIntro,residential:t.resText,commercial:t.comText,about:t.aboutText,areas:t.areasText,contact:t.contactIntro,privacy:t.pending}[page||'home']);return {title:`${title} | Aqua Pro Plumbing`,description,alternates:{canonical:siteUrl+route(lang,service?serviceSlug(service,lang):page||'home'),languages:Object.fromEntries((['en','es'] as Lang[]).map(l=>[l,siteUrl+route(l,service?serviceSlug(service,l):page||'home')]))},openGraph:{title,description,locale:lang==='es'?'es_ES':'en_US',type:'website',images:[{url:siteUrl+'/images/kitchen.webp',width:1400,height:2104}]}};}
export default async function PageView({params}:Props){const {lang:raw,slug}=await params;if(raw!=='en'&&raw!=='es')notFound();const lang=raw as Lang;const {page,service}=resolve(lang,slug);if(!page&&!service)notFound();const schema=businessStructuredData();return <>{schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>}<script dangerouslySetInnerHTML={{__html:`document.documentElement.lang=${JSON.stringify(lang)}`}}/><Site lang={lang} page={service?'service':page!} serviceId={service?.id}/></>}
