'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,ChevronDown,Menu,X,Check,House,Building2,Droplets,Wrench,Waves,Thermometer,Camera,Gauge,Construction,MapPin,Phone} from 'lucide-react';
import {copy,services,route,serviceSlug,Lang,Page} from '../lib/content';
import {experience,serviceGroups,relatedServices,prepare,media,serviceMedia,MediaKey} from '../lib/experience';
import {base,company,siteUrl} from '../lib/config';
import RequestForm from './RequestForm';
import CommercialProof from './CommercialProof';
const icons=[Construction,Droplets,Waves,Wrench,Thermometer,Camera,Gauge];
export default function Site({lang:initialLang,page,serviceId}:{lang:Lang;page:Page|'service';serviceId?:string}){
 const [lang,setLang]=useState(initialLang); const v=experience[lang];const [filter,setFilter]=useState('all');const [property,setProperty]=useState('residential');
 const t=copy[lang],other:Lang=lang==='en'?'es':'en'; const [menu,setMenu]=useState(false);const [query,setQuery]=useState('');const service=services.find(s=>s.id===serviceId);const [selection,setSelection]=useState('');
 useEffect(()=>{if(page!=='contact')return;const pop=()=>{setLang(window.location.pathname.includes('/es/')?'es':'en');};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[page]);
 useEffect(()=>{if(page!=='contact')return;document.title=copy[lang].request+' | Aqua Pro Plumbing';document.querySelector('meta[name=description]')?.setAttribute('content',copy[lang].contactIntro);document.querySelector('link[rel=canonical]')?.setAttribute('href',siteUrl+route(lang,'contact'));document.querySelector('meta[property="og:title"]')?.setAttribute('content',copy[lang].request);document.querySelector('meta[property="og:description"]')?.setAttribute('content',copy[lang].contactIntro);document.querySelector('meta[property="og:locale"]')?.setAttribute('content',lang==='es'?'es_ES':'en_US');},[lang,page]);
 useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('aqua-language',lang);}catch{}setQuery(window.location.search);const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[lang]);
 const link=(p:Page|string)=>base+route(lang,p);
 const request=(id?:string,propertyType?:string,intent='service')=>{const chosen=id||service?.id||selection||undefined;const place=propertyType||(page==='residential'||page==='commercial'?page:page==='home'&&selection?property:undefined);const params=new URLSearchParams({...chosen?{service:chosen}:{},...place?{property:place}:{},...intent==='quote'?{intent}:{}});return link('contact')+(params.size?'?'+params.toString():'');};
 const languageLink=base+route(other,page==='service'&&service?serviceSlug(service,other):page)+query;
 const switchLanguage=(e:React.MouseEvent<HTMLAnchorElement>)=>{if(page!=='contact'||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();window.history.pushState(null,'',languageLink);setLang(other);};
 const cta=(id?:string,property?:string,label?:string)=><a className="button" href={request(id,property,label===t.quote?'quote':'service')}>{label||t.request}<ArrowUpRight size={18}/></a>;
 const photo=(cls='',key:MediaKey='technician')=><figure className={'photo '+cls}><img src={base+'/images/'+media[key].src} width="1400" height="1000" alt={media[key][lang]} loading={cls==='hero-photo'?'eager':'lazy'}/><figcaption>{v.photo}</figcaption></figure>;
 const grid=(subset=services)=><div className="service-grid">{subset.map(s=>{const Icon=icons[services.indexOf(s)];return <a className="service-card" href={link(serviceSlug(s,lang))} key={s.id}><div className="service-card-image"><img src={base+'/images/'+media[serviceMedia[s.id]].src} width="600" height="400" loading="lazy" alt={media[serviceMedia[s.id]][lang]}/><span><Icon size={22} strokeWidth={1.5}/></span><small>{v.photo}</small></div><div className="service-card-body"><h3>{s[lang].name}</h3><p>{s[lang].short}</p><span>{v.learn}<ArrowUpRight size={18}/></span></div></a>})}</div>;
 const chosenService=services.find(s=>s.id===selection);
 const finder=()=><div className="problem-finder"><div className="finder-title"><Droplets size={23}/><div><h2>{v.start}</h2><p>{v.startHint}</p></div></div><div className="problem-options">{t.choices.map((label,i)=>{const id=['leak-detection','drain-cleaning','new-plumbing','water-heaters','camera-inspection','unsure'][i];return <button type="button" key={id} aria-pressed={selection===id} onClick={()=>setSelection(id)}>{label}<ArrowUpRight size={16}/></button>})}</div>{selection&&<div className="finder-result" aria-live="polite"><strong>{v.recommend}: {chosenService?.[lang].name||t.notSure}</strong>{chosenService&&<p>{chosenService[lang].short}</p>}<label htmlFor="finder-property">{v.chooseProperty}</label><select id="finder-property" value={property} onChange={e=>setProperty(e.target.value)}><option value="residential">{t.residential}</option><option value="commercial">{t.commercial}</option></select><a className="button" href={request(selection,property)}>{v.continue}<ArrowRight size={17}/></a>{chosenService&&<a className="finder-learn" href={link(serviceSlug(chosenService,lang))}>{v.change}</a>}<p className="fine">{v.notDiagnosis}</p></div>}</div>;
 const filters=()=><div className="service-filters" role="group" aria-label={t.nav[1]}>{(['all','repair','install','comfort'] as const).map(f=><button key={f} type="button" aria-pressed={filter===f} onClick={()=>setFilter(f)}>{v[f]}</button>)}</div>;
 const process=()=><section className="section process reveal"><div className="section-top"><span className="kicker">{lang==='en'?'Simple from the start':'Sencillo desde el inicio'}</span><h2>{t.how}</h2></div><div className="process-grid">{t.steps.map((s,i)=><div key={s}><span className="step-number">0{i+1}</span><h3>{s}</h3><p>{t.stepTexts[i]}</p></div>)}</div><p className="fine">{t.booking}</p></section>;
 const questions=(pairs=t.faqPairs)=><section className="section faq reveal"><div><span className="kicker">{lang==='en'?'Common questions':'Preguntas frecuentes'}</span><h2>{t.faq}</h2><p>{lang==='en'?'A good decision starts with useful information.':'Una buena decisión comienza con información útil.'}</p></div><div>{pairs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</div></section>;
 const properties=()=><section className="property-grid section reveal">{['residential','commercial'].map((p,i)=><article className={'property-panel '+(i?'commercial':'')} key={p}>{i?<Building2 size={35}/>:<House size={35}/>}<span className="kicker">{i?t.commercial:t.residential}</span><h2>{i?t.com:t.res}</h2><p>{i?t.comText:t.resText}</p><a href={link(p as Page)} className="text-link">{i?t.nav[3]:t.nav[2]}<ArrowUpRight size={19}/></a></article>)}</section>;
 const closer=()=><section className="closer"><div className="container"><div><span className="kicker">Aqua Pro Plumbing</span><h2>{t.close}</h2><p>{t.closeText}</p></div>{cta()}</div></section>;
 return <><a className="skip" href="#main">{lang==='en'?'Skip to content':'Ir al contenido'}</a><div className="topline"><div className="container"><span>{t.values[0]}</span><a href={link('areas')}><MapPin size={13}/>{t.areas}</a></div></div><header><div className="container header-inner"><a href={link('home')} aria-label="Aqua Pro Plumbing"><img className="logo" src={base+company.logo} width="210" height="82" alt="Aqua Pro Plumbing"/></a><nav aria-label={lang==='en'?'Main navigation':'Navegación principal'} className={menu?'open':''}>{(['home','services','residential','commercial','about','contact'] as Page[]).map((p,i)=>p==='services'?<div className="dropdown" key={p}><a href={link(p)} aria-current={page===p||(p==='services'&&page==='service')?'page':undefined}>{t.nav[i]}</a><details><summary aria-label={t.nav[i]}><ChevronDown size={14}/></summary><div className="dropdown-menu"><a href={link('services')}>{t.all}</a>{services.map(s=><a key={s.id} href={link(serviceSlug(s,lang))}>{s[lang].name}</a>)}</div></details></div>:<a key={p} href={link(p)} aria-current={page===p?'page':undefined}>{t.nav[i]}</a>)}</nav><div className="header-actions"><a className="language" href={languageLink} onClick={switchLanguage} lang={other} aria-label={other==='es'?'Cambiar a español':'Switch to English'}><span className={lang==='en'?'selected':''}>EN</span><i>/</i><span className={lang==='es'?'selected':''}>ES</span></a><div className="desktop-cta">{cta()}</div><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={lang==='en'?'Toggle menu':'Abrir o cerrar menú'}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main id="main">
 {page==='home'&&<><section className="hero container hero-v2"><div className="hero-copy"><span className="kicker">{t.values[0]}</span><h1>{v.headline}</h1><p>{v.intro}</p>{finder()}<div className="hero-links"><a className="text-link" href={link('services')}>{t.explore}<ArrowRight size={18}/></a><a href={request(undefined,undefined,'quote')}>{t.quote}</a></div></div><div className="hero-visual">{photo('hero-photo')}<div className="photo-caption"><Droplets size={22}/><span>{lang==='en'?'From the first question to the next step.':'Desde la primera pregunta hasta el siguiente paso.'}</span></div></div></section><div className="value-strip"><div className="container">{t.values.map(s=><span key={s}><Check size={18}/>{s}</span>)}</div></div><section className="section container reveal"><div className="section-top split"><div><span className="kicker">{t.nav[1]}</span><h2>{t.serviceTitle}</h2></div><p>{t.serviceIntro}</p></div>{grid()}</section><div className="container">{properties()}</div><section className="assistant-section"><div className="container coverage-panel"><MapPin size={40}/><div><h2>{v.coverage}</h2><p>{v.coverageText}</p></div><a className="button secondary" href={link('areas')}>{t.areas}<ArrowUpRight size={18}/></a></div></section><div className="container">{process()}<section className="why section reveal">{photo('','bathroom')}<div><span className="kicker">{lang==='en'?'The Aqua Pro approach':'El enfoque Aqua Pro'}</span><h2>{t.why}</h2><p>{t.whyText}</p><ul className="check-list">{t.whyItems.map(s=><li key={s}><Check size={18}/>{s}</li>)}</ul><a className="text-link" href={link('about')}>{t.nav[4]}<ArrowUpRight size={18}/></a></div></section>{questions()}</div>{closer()}</>}
 {page==='services'&&<><section className="page-heading container"><span className="kicker">{t.nav[1]}</span><h1>{t.serviceTitle}</h1><p>{t.serviceIntro}</p><div className="service-picker"><label htmlFor="quick-service">{t.help}</label><select id="quick-service" value={selection} onChange={e=>setSelection(e.target.value)}><option value="">{t.service}</option>{services.map(s=><option key={s.id} value={s.id}>{s[lang].name}</option>)}</select>{cta(selection||'unsure')}</div></section><div className="container services-page">{filters()}<p className="filter-count" role="status">{services.filter(s=>filter==='all'||serviceGroups[s.id]===filter).length} {v.count}</p>{grid(services.filter(s=>filter==='all'||serviceGroups[s.id]===filter))}{process()}</div>{closer()}</>}
 {page==='service'&&service&&<><section className="container detail-hero"><div><nav className="breadcrumbs" aria-label={lang==='en'?'Breadcrumb':'Ruta de navegación'}><a href={link('home')}>{t.nav[0]}</a><span>/</span><a href={link('services')}>{t.nav[1]}</a><span>/</span><span aria-current="page">{service[lang].name}</span></nav><h1>{service[lang].name}</h1><h2>{service[lang].short}</h2><p>{service[lang].description}</p>{cta(service.id)}</div>{photo('service-photo',serviceMedia[service.id])}</section><div className="container"><section className="section detail-columns"><div><h2>{t.signs}</h2><ul className="check-list">{service[lang].signs.map(s=><li key={s}><Check size={18}/>{s}</li>)}</ul></div><div><h2>{t.work}</h2><ul className="check-list">{service[lang].work.map(s=><li key={s}><Check size={18}/>{s}</li>)}</ul><p className="fine">{lang==='en'?'All work is subject to evaluation and an agreed scope.':'Todo trabajo está sujeto a evaluación y un alcance acordado.'}</p></div></section><section className="service-preparation"><div><span className="kicker">{v.prepare}</span><h2>{v.scope}</h2><p>{v.scopeText}</p>{cta(service.id,undefined,t.quote)}</div><ul className="check-list">{prepare[service.id][lang].map(item=><li key={item}><Check size={20}/>{item}</li>)}</ul></section>{process()}{questions([[service[lang].faq,service[lang].answer],t.faqPairs[6]])}<section className="section"><h2>{t.related}</h2>{grid((relatedServices[service.id]||[]).map(id=>services.find(s=>s.id===id)!))}</section></div>{closer()}</>}
 {(page==='residential'||page==='commercial')&&<><section className="container detail-hero"><div><span className="kicker">{page==='residential'?t.residential:t.commercial}</span><h1>{page==='residential'?t.res:t.com}</h1><p>{page==='residential'?t.resText:t.comText}</p><p>{page==='residential'?(lang==='en'?'From everyday leaks to kitchen and bathroom upgrades, begin with the needs of your home.':'Desde fugas cotidianas hasta mejoras en cocina y baño, comienza con las necesidades de tu hogar.'):(lang==='en'?'Tell us about access, operating hours and maintenance needs so the work can be reviewed around your property.':'Cuéntanos sobre accesos, horarios de operación y mantenimiento para revisar el trabajo según tu propiedad.')}</p>{cta(undefined,page)}</div>{photo('',page==='residential'?'bathroom':'technician')}</section><div className="container"><section className="section"><h2>{t.nav[1]}</h2>{grid()}</section>{process()}</div>{closer()}</>}
 {page==='about'&&<><section className="container detail-hero"><div><span className="kicker">{t.nav[4]}</span><h1>{t.about}</h1><p>{t.aboutText}</p>{cta()}</div>{photo()}</section><div className="container"><section className="section about-values"><h2>{t.why}</h2><ul className="check-list">{t.whyItems.map(s=><li key={s}><Check/>{s}</li>)}</ul></section>{process()}</div>{closer()}</>}
 {page==='areas'&&<><section className="container page-heading narrow"><MapPin size={40}/><h1>{t.areasTitle}</h1><p>{t.areasText}</p>{company.serviceAreas.length>0&&<ul>{company.serviceAreas.map(a=><li key={a}>{a}</li>)}</ul>}{cta()}</section>{closer()}</>}
 {page==='contact'&&<section className="container contact-layout"><div className="contact-copy"><span className="kicker">{t.nav[5]}</span><h1>{v.contactTitle}</h1><p>{t.contactIntro}</p><div className="contact-help"><Droplets size={30}/><h3>{t.values[1]}</h3><p>{t.booking}</p><a href={link('areas')}>{t.areas}<ArrowUpRight size={15}/></a>{company.phone&&<a href={'tel:'+company.phone}>{company.phone}</a>}{company.email&&<a href={'mailto:'+company.email}>{company.email}</a>}</div></div><RequestForm lang={lang}/></section>}
 {page==='privacy'&&<article className="container page-heading narrow"><span className="kicker">{t.pending}</span><h1>{t.privacy}</h1><p>{t.privacyText}</p><a className="text-link" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">{lang==='en'?'GitHub privacy statement':'Declaración de privacidad de GitHub'}<ArrowUpRight size={16}/></a></article>}
 {(page==='home'||page==='about')&&<CommercialProof lang={lang}/>}</main><footer><div className="container footer-grid"><div><a href={link('home')}><img className="logo" src={base+company.logo} width="210" height="82" alt="Aqua Pro Plumbing"/></a><p>{t.footer}</p></div><div><h3>{t.nav[1]}</h3>{services.map(s=><a key={s.id} href={link(serviceSlug(s,lang))}>{s[lang].name}</a>)}</div><div><h3>{lang==='en'?'Explore':'Explorar'}</h3>{(['about','residential','commercial','areas','contact'] as Page[]).map(p=><a href={link(p)} key={p}>{p==='areas'?t.areas:p==='about'?t.nav[4]:p==='contact'?t.nav[5]:p==='residential'?t.residential:t.commercial}</a>)}<a href={languageLink} onClick={switchLanguage} lang={other}>{other==='es'?'Español':'English'}</a></div><div><h3>{t.help}</h3><p>{t.closeText}</p>{cta(undefined,undefined,t.quote)}{company.phone&&<a href={'tel:'+company.phone}>{company.phone}</a>}{company.email&&<a href={'mailto:'+company.email}>{company.email}</a>}{company.address&&<p>{company.address}</p>}{company.hours&&<p>{company.hours}</p>}{company.socials.map(s=><a key={s.url} href={s.url}>{s.label}</a>)}</div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Aqua Pro Plumbing</span><a href={link('privacy')}>{t.privacy}</a></div></footer>{page!=='contact'&&<div className="mobile-bar">{company.phone?<a href={'tel:'+company.phone}><Phone size={18}/>{lang==='en'?'Call':'Llamar'}</a>:<a href={link('services')}>{t.nav[1]}</a>}{cta(service?.id,page==='residential'||page==='commercial'?page:undefined)}</div>}</>;
}
