import {chromium,expect} from '@playwright/test';
const b=await chromium.launch({channel:'chrome'});const p=await b.newPage({viewport:{width:1440,height:1000}});const root=process.env.TEST_URL||'http://127.0.0.1:4173/plumbing';const errors=[];p.on('pageerror',e=>errors.push(e.message));const sent=[];p.on('request',r=>{if(r.method()==='POST')sent.push(r.url())});
await p.goto(root+'/en/');await p.getByRole('button',{name:'I have a leak',exact:true}).click();await expect(p.locator('.finder-result')).toContainText('Leak Detection & Repair');await p.locator('#finder-property').selectOption('commercial');await p.getByRole('link',{name:'Continue with this service'}).click();await expect(p.locator('#service')).toHaveValue('leak-detection');await expect(p.locator('input[value=commercial]')).toBeChecked();
await p.locator('#intent').selectOption('quote');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.locator('#description').fill('Demo V2: check a pipe connection');await p.locator('#city').fill('Demo City');await p.locator('#zip').fill('12345');await p.getByRole('link',{name:'Cambiar a español'}).click();await expect(p).toHaveURL(/\/es\/contacto\//);await expect(p.locator('#description')).toHaveValue('Demo V2: check a pipe connection');await expect(p.locator('li[aria-current=step]')).toContainText('Detalles');await expect(p.locator('html')).toHaveAttribute('lang','es');await expect(p).toHaveTitle(/Solicitar servicio/);
await p.goBack();await expect(p.locator('html')).toHaveAttribute('lang','en');await expect(p.locator('#city')).toHaveValue('Demo City');await p.goForward();await expect(p.locator('html')).toHaveAttribute('lang','es');await expect(p.locator('#zip')).toHaveValue('12345');
await p.getByRole('button',{name:'Continuar',exact:true}).click();await p.locator('#name').fill('Demo User');await p.locator('#email').fill('demo@example.com');await p.locator('#consent').check();await p.getByRole('link',{name:'Switch to English'}).click();await expect(p.locator('#email')).toHaveValue('demo@example.com');await expect(p.locator('#consent')).toBeChecked();await p.getByRole('button',{name:'Continue',exact:true}).click();await expect(p.locator('.review')).toContainText('Request a quote');await expect(p.locator('.review')).toContainText('Commercial');await p.getByRole('link',{name:'Cambiar a español'}).click();await expect(p.locator('.review')).toContainText('Solicitar cotización');await p.getByRole('button',{name:'Completar solicitud de demostración',exact:true}).click();await expect(p.locator('.success')).toBeVisible();await p.getByRole('link',{name:'Switch to English'}).click();await expect(p.locator('.success')).toContainText('Demo request completed');
// Phone-only route: email is optional and the intent is seeded by the CTA.
await p.goto(root+'/en/services/water-heaters/');const hrefs=await p.locator('a.button').evaluateAll(as=>as.map(a=>a.href));if(hrefs.some(h=>!h.includes('service=water-heaters')))throw new Error('Context missing '+hrefs.join('\n'));await expect(p.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Services',exact:true}).first()).toHaveAttribute('aria-current','page');await p.getByRole('link',{name:'Request a Quote',exact:true}).first().click();await expect(p.locator('#intent')).toHaveValue('quote');await p.locator('input[value=residential]').check();await p.getByRole('button',{name:'Continue',exact:true}).click();await p.locator('#description').fill('Demo equipment assessment');await p.locator('#city').fill('Demo City');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.locator('#method').selectOption('phone');await p.locator('#name').fill('Demo User');await p.locator('#phone').fill('2025550123');await p.locator('#consent').check();await p.getByRole('button',{name:'Continue',exact:true}).click();await expect(p.locator('.review')).toBeVisible();await p.getByRole('button',{name:'Complete demo request',exact:true}).click();await expect(p.locator('.success')).toBeVisible();
await p.goto(root+'/en/residential/');const propertyHrefs=await p.locator('a.button').evaluateAll(as=>as.map(a=>a.href));if(propertyHrefs.some(h=>!h.includes('property=residential')))throw new Error('Property lost');
await p.goto(root+'/en/services/');await p.getByRole('button',{name:'Hot water & water control',exact:true}).click();await expect(p.locator('.service-card')).toHaveCount(2);await p.getByRole('button',{name:'Leaks & drainage',exact:true}).click();await expect(p.locator('.service-card')).toHaveCount(3);
for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:900});for(const route of ['/en/','/es/','/en/services/','/es/servicios/calentadores/','/es/contacto/']){await p.goto(root+route);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Overflow '+width+route);await p.locator('img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading="eager";return i.decode().catch(()=>{});})));if(await p.locator('img').evaluateAll(imgs=>imgs.some(i=>!i.naturalWidth)))throw new Error('Image '+route)}}
await p.setViewportSize({width:1440,height:1000});await p.goto(root+'/en/');await p.screenshot({path:'/tmp/aqua-v2-desktop.png',fullPage:true});await p.screenshot({path:'/tmp/aqua-v2-desktop-fold.png'});await p.setViewportSize({width:390,height:844});await p.goto(root+'/es/');await p.screenshot({path:'/tmp/aqua-v2-mobile.png'});await p.getByRole('button',{name:'Tengo una fuga',exact:true}).click();await p.screenshot({path:'/tmp/aqua-v2-finder.png',fullPage:true});
const storage=await p.evaluate(()=>({local:{...localStorage},session:{...sessionStorage}}));if(Object.keys(storage.local).some(k=>k!=='aqua-language')||Object.keys(storage.session).length)throw new Error('Unexpected storage');if(sent.length)throw new Error('POST '+sent);if(errors.length)throw new Error(errors.join('\n'));console.log('PASS V2: finder; language preservation at details/contact/review/completion; history back/forward; service/property context; quote intent; email-only and phone-only; filters; 5 widths; no persisted PII, no POST, no browser errors');await b.close();
