import { chromium } from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const root=process.env.TEST_URL||'http://127.0.0.1:4173/plumbing';
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(root+'/en/');await page.screenshot({path:'/tmp/aqua-desktop.png',fullPage:true});
const links=await page.locator('a').evaluateAll(as=>[...new Set(as.map(a=>a.href).filter(h=>h.startsWith(location.origin)&&!h.includes('#')))]);
for(const url of links){const r=await page.request.get(url);if(r.status()!==200)throw new Error(url+' '+r.status());}
await page.getByRole('link',{name:'Cambiar a español'}).click();await page.waitForURL('**/es/');if(await page.locator('html').getAttribute('lang')!=='es')throw new Error('language');
await page.goto(root+'/en/services/leak-detection/');await page.getByRole('link',{name:'Cambiar a español'}).click();await page.waitForURL('**/es/servicios/reparacion-fugas/');
await page.goto(root+'/en/contact/?service=drain-cleaning&property=residential');
await page.waitForFunction(()=>document.querySelector('#service')?.value==='drain-cleaning');
await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();if(!await page.locator('#description-error').isVisible())throw new Error('missing validation');
await page.locator('#description').fill('Demo only: slow kitchen drain.');await page.locator('#city').fill('Demo city');await page.getByRole('button',{name:'Back',exact:true}).click();if(await page.locator('#service').inputValue()!=='drain-cleaning')throw new Error('selection lost');await page.getByRole('button',{name:'Continue',exact:true}).click();if(await page.locator('#description').inputValue()!=='Demo only: slow kitchen drain.')throw new Error('details lost');await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.locator('#name').fill('Demo User');await page.locator('#email').fill('invalid');await page.locator('#phone').fill('123');await page.getByRole('button',{name:'Continue',exact:true}).click();if(!await page.locator('#email-error').isVisible())throw new Error('email validation');
await page.locator('#email').fill('demo@example.com');await page.locator('#phone').fill('2025550123');await page.locator('#consent').check();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Edit',exact:true}).first().click();if(await page.locator('#service').inputValue()!=='drain-cleaning')throw new Error('review edit');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();
const outgoing=[];page.on('request',r=>{if(r.method()==='POST')outgoing.push(r.url())});await page.getByRole('button',{name:'Complete demo request',exact:true}).click();await page.getByRole('heading',{name:'Demo request completed. No appointment has been booked.'}).waitFor();if(outgoing.length)throw new Error('outgoing form request');const storage=await page.evaluate(()=>({...localStorage}));if(Object.keys(storage).some(k=>k!=='aqua-language'))throw new Error('unexpected storage');
await page.setViewportSize({width:390,height:844});await page.goto(root+'/es/');await page.screenshot({path:'/tmp/aqua-mobile.png',fullPage:true});await page.getByRole('button',{name:'Abrir o cerrar menú'}).click();await page.getByRole('navigation').getByRole('link',{name:'Comercial',exact:true}).click();await page.waitForURL('**/es/comercial/');
for(const lang of ['en','es']){await page.goto(root+'/'+lang+'/');const paths=await page.locator('a').evaluateAll(as=>[...new Set(as.map(a=>a.href).filter(h=>h.startsWith(location.origin)&&!h.includes('#')))]);for(const url of paths){await page.goto(url);const over=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(over)throw new Error('overflow '+url);await page.locator('img').evaluateAll(async imgs=>Promise.all(imgs.map(i=>{i.loading="eager";return i.decode().catch(()=>{});})));const bad=await page.locator('img').evaluateAll(imgs=>imgs.some(i=>!i.complete||i.naturalWidth===0));if(bad)throw new Error('broken image '+url);}}
await page.goto(root+'/es/contacto/?service=water-heaters&property=commercial');await page.waitForFunction(()=>document.querySelector('#service')?.value==='water-heaters');await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.locator('#description').fill('Prueba del calentador');await page.locator('#city').fill('Ciudad de prueba');await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.locator('#name').fill('Usuario Demo');await page.locator('#email').fill('demo@example.com');await page.locator('#phone').fill('2025550123');await page.locator('#consent').check();await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.screenshot({path:'/tmp/aqua-form-mobile.png',fullPage:true});await page.getByRole('button',{name:'Completar solicitud de demostración',exact:true}).click();await page.getByRole('heading',{name:'Solicitud de demostración completada. No se ha reservado ninguna cita.'}).waitFor();
if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({result:'PASS',desktopLinks:links.length,viewports:['1440x1000','390x844'],checks:['all linked localized routes HTTP 200','no mobile horizontal overflow','no broken images','equivalent language route','mobile navigation','preselected service and property','required/email/phone/consent validation','data preservation and editable review','EN and ES completion','no POST submission','language-only local storage','no browser errors']},null,2));await browser.close();
